user root root;
worker_processes auto;
pcre_jit on;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
    multi_accept on;
    use epoll;
}

http {
    access_log /dev/stdout;
    include /etc/nginx/conf.d/*.conf;
}
